apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: production-grade-app

type: Opaque

stringData:
  DB_HOST: production-grade-db.c3cakg8qymrd.ap-southeast-1.rds.amazonaws.com
  DB_PORT: "3306"
  DB_NAME: productiongradedb
  DB_USER: admin
  DB_PASSWORD: YourStrongPassword123!
